gv_ville:
    resource: "@GVVilleBundle/Resources/config/routing.yml"
    prefix:   /ville

gv_user:
    resource: "@GVUserBundle/Resources/config/routing.yml"
    prefix:   /

gv_forum:
    resource: "@GVForumBundle/Resources/config/routing.yml"
    prefix:   /Forum


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
login:
    pattern: /login
    defaults: {_controller: GVUserBundle:Default:login}
login_check:
    pattern: /login_check
logout:
    pattern: /logout
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
